name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

#    - name: Install dependencies
#      run: |
#        # Install your project's dependencies here.
#
#    - name: Run tests
#      run: |
#        # Run your tests here.
#        # In your tests, connect to PostgreSQL using:
#        # Host: localhost
#        # Port: 5432
#        # User: user
#        # Password: password
#        # Database: testdb
